#!/usr/bin/env python3
"""
Generate Pydantic models from the mpak registry OpenAPI spec.

This script fetches the OpenAPI spec from the live registry API and generates
Pydantic models using datamodel-code-generator. The generated types are written
to src/mpak/generated/types.py.

Usage:
    python scripts/generate-types.py [--url URL]

Options:
    --url URL   OpenAPI spec URL (default: https://registry.mpak.dev/docs/json)
"""

import argparse
import subprocess
import sys
import urllib.request
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description="Generate Pydantic models from OpenAPI spec")
    parser.add_argument(
        "--url",
        default="https://registry.mpak.dev/docs/json",
        help="OpenAPI spec URL (default: https://registry.mpak.dev/docs/json)",
    )
    args = parser.parse_args()

    # Resolve paths
    script_dir = Path(__file__).parent
    sdk_root = script_dir.parent
    output_file = sdk_root / "src" / "mpak" / "generated" / "types.py"

    print(f"Fetching OpenAPI spec from {args.url}...")
    try:
        with urllib.request.urlopen(args.url) as resp:
            spec_content = resp.read()
        print(f"✓ Fetched {len(spec_content)} bytes")
    except Exception as e:
        print(f"✗ Failed to fetch OpenAPI spec: {e}", file=sys.stderr)
        sys.exit(1)

    # Generate Pydantic models
    print(f"Generating Pydantic models to {output_file}...")
    try:
        result = subprocess.run(
            [
                "datamodel-codegen",
                "--url",
                args.url,
                "--output",
                str(output_file),
                "--target-python-version",
                "3.11",
                "--use-standard-collections",
                "--use-schema-description",
                "--input-file-type",
                "openapi",
                "--output-model-type",
                "pydantic_v2.BaseModel",
                "--field-constraints",
                "--use-default",
                "--collapse-root-models",
                "--strict-nullable",
                "--openapi-scopes",
                "paths",
                "--reuse-model",
            ],
            check=True,
            capture_output=True,
            text=True,
        )
        print(f"✓ Generated {output_file}")
        if result.stdout:
            print(result.stdout)
    except subprocess.CalledProcessError as e:
        print(f"✗ Failed to generate types: {e}", file=sys.stderr)
        if e.stderr:
            print(e.stderr, file=sys.stderr)
        sys.exit(1)
    except FileNotFoundError:
        print(
            "✗ datamodel-code-generator not found. Install dev dependencies: uv pip install -e '.[dev]'",
            file=sys.stderr,
        )
        sys.exit(1)

    # Post-process: replace EmailStr with str (avoids email-validator dependency)
    print("Post-processing generated types...")
    content = output_file.read_text()
    content = content.replace("    EmailStr,\n", "").replace("EmailStr", "str")

    # Add header comment
    header = '''"""
Generated Pydantic models from mpak registry OpenAPI spec.

DO NOT EDIT THIS FILE MANUALLY.
Regenerate with: python scripts/generate-types.py

Source: https://registry.mpak.dev/docs/json
"""

'''
    output_file.write_text(header + content)

    print("✓ Type generation complete!")
    print(f"\nGenerated file: {output_file}")


if __name__ == "__main__":
    main()
